IDEIBiblio/IDEIBiblio/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;
using IDEIBiblio.AuthorizeAttributes;
using System.IO;

namespace IDEIBiblio.Controllers
{
    public class BookController : Controller
    {
        private IDEIBiblioDbContext db = new IDEIBiblioDbContext();

        //
        // GET: /Default1/

        public ActionResult Index()
        {
            ViewBag.Title = "Books";
            ViewBag.Message = "Featured:";
            return View(db.Books.ToList());
        }

        //
        // GET: /Default1/

        public ActionResult Featured()
        {
            ViewBag.Title = "Books";
            ViewBag.Message = "Featured:";
            ICollection<Book> books = db.GetMostOrderedBooks();
            return PartialView(books);
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.Discount = book.DiscountPercentage * 100;
            return View(book);
        }

        //
        // GET: /Default1/Create
        [AuthorizeRole]
        public ActionResult Create()
        {
            
            SelectList PublisherList = new SelectList(db.Publishers.ToList(), "PublisherID", "Name");
            SelectList AuthorsList = new SelectList(db.Authors.ToList(), "AuthorID", "Name");
            SelectList CategoriesList = new SelectList(db.BookCategories.ToList(), "BookCategoryID", "Name");

            ViewBag.PublisherList = PublisherList;
            ViewBag.AuthorsList = AuthorsList;
            ViewBag.CategoriesList = CategoriesList;

            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        //
        // GET: /Default1/Edit/5
        //[Authorize(Roles="admin,product_manager")]
        [AuthorizeRole]
        public ActionResult Edit(int id = 0)
        {
            Book book = db.Books.Find(id);


            SelectList PublisherList = new SelectList(db.Publishers.ToList(), "PublisherID", "Name");
            SelectList AuthorsList = new SelectList(db.Authors.ToList(), "AuthorID", "Name");
            SelectList CategoriesList = new SelectList(db.BookCategories.ToList(), "BookCategoryID", "Name");

            ViewBag.PublisherList = PublisherList;
            ViewBag.AuthorsList = AuthorsList;
            ViewBag.CategoriesList = CategoriesList;

            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
//            Book book = db.Books.Create();
            if (ModelState.IsValid)
            {                
//                db.Entry(book).CurrentValues.SetValues(viewbook);
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        //
        // GET: /Default1/Delete/5
        [AuthorizeRole]
        public ActionResult Delete(int id = 0)
        {
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AuthorizeRole]
        public ActionResult CreatePublisher()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreatePublisher(Publisher publisher)
        {
            if (ModelState.IsValid)
            {               
                db.Publishers.Add(publisher);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return Json(new { element = "PublisherID", id = publisher.PublisherID, name = publisher.Name });
        }

        [AuthorizeRole]
        public ActionResult CreateAuthor()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return Json(new { element = "AuthorID", id = author.AuthorID, name = author.Name });
        }

        [AuthorizeRole]
        public ActionResult CreateCategory()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateCategory(BookCategory category)
        {
            if (ModelState.IsValid)
            {
                db.BookCategories.Add(category);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return Json(new { element = "BookCategoryID", id = category.BookCategoryID, name = category.Name });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    }
}

IDEIBiblio/IDEIBiblio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;
using IDEIBiblio.Models;

namespace IDEIBiblio.Controllers
{
    public class HomeController : Controller
    {
        private IDEIBiblioDbContext db = new IDEIBiblioDbContext();

        public ActionResult Index()
        {
            ViewBag.Title = "Welcome!";
            ViewBag.Message = "";
            return View(db.Products.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

IDEIBiblio/IDEIBiblio/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;
using IDEIBiblio.AuthorizeAttributes;

namespace IDEIBiblio.Controllers
{
    public class MagazineController : Controller
    {
        private IDEIBiblioDbContext db = new IDEIBiblioDbContext();

        //
        // GET: /Magazine/

        public ActionResult Index()
        {
            ViewBag.Title = "Magazines";
            ViewBag.Message = "Featured:";
            return View(db.Magazines.ToList());
        }

        //
        // GET: /Default1/

        public ActionResult Featured()
        {
            ViewBag.Title = "Magazines";
            ViewBag.Message = "Featured:";
            ICollection<Magazine> Magazines = db.GetMostOrderedMagazines();
            return PartialView(Magazines);
        }

        //
        // GET: /Magazine/Details/5

        public ActionResult Details(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            ViewBag.Discount = magazine.DiscountPercentage * 100;
            return View(magazine);
        }

        //
        // GET: /Magazine/Create
        [AuthorizeRole]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Magazine/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Magazine magazine)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(magazine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(magazine);
        }

        //
        // GET: /Magazine/Edit/5
        [AuthorizeRole]
        public ActionResult Edit(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            return View(magazine);
        }

        //
        // POST: /Magazine/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Magazine magazine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(magazine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(magazine);
        }

        //
        // GET: /Magazine/Delete/5
        [AuthorizeRole]
        public ActionResult Delete(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            return View(magazine);
        }

        //
        // POST: /Magazine/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Magazine magazine = db.Magazines.Find(id);
            db.Products.Remove(magazine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIBiblio/IDEIBiblio/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

IDEIBiblio/IDEIBiblio/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Sales:</span>
        <span><a href="mailto:Sales@ideibiblio.com">sales@ideibiblio.com</a></span>
    </p>
    <p>
        <span class="label">Webmaster:</span>
        <span><a href="mailto:webmaster@ideibiblio.com">webmaster@ideibiblio.com</a></span>
    </p>
    <p>
        <span class="label">General contact:</span>
        <span><a href="mailto:General@ideibiblio.com">general@ideibiblio.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        Rua Dr. António Bernardino de Almeida, 431 <br />
        4200-072 Porto <br />
        Portugal
    </p>
</section>

<section class="contact">
    <header>
        <h3>Our location!</h3>
    </header>
    <div class="fluid-wrapper">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12011.51598457644!2d-8.612069024045846!3d41.18080636267975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd246449b419e1c1%3A0x16a6fd2fcace4efe!2sInstituto+superior+de+engenharia+do+porto!5e0!3m2!1sen!2spt!4v1386190921733" width="600" height="450" frameborder="0" style="border:0"></iframe>
    </div>
</section>

IDEIBiblio/IDEIBiblio/Views/Home/Index.cshtml
@using IDEIBiblio.Helpers
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
                <p>Welcome to the <b>IDEIBiblio</b> book shop - Your one stop location for all sorts of publications!</p>
                
            </hgroup>  
        </div>
    </section>
}

<div class="homeview-group">
    <div class="homeview-widget">
        <iframe src="http://uvm095.dei.isep.ipp.pt/iframe.html" height="520" width="310" style="border: none; outline: none; overflow: hidden;"></iframe>
    </div>
    <div class="homeview-cell">
        <h3>Hot publications:</h3>
        <ul class="round">
            <li>
                <h5>Books</h5>
                @Html.Action("Featured", "Book")                      
            </li>

            <li>
                <h5>Magazines</h5>
                @Html.Action("Featured", "Magazine")
            </li>

            <li>
                <h5>Categories</h5>
        
            </li>
        </ul>
    </div>

</div>