IDEIBiblio/IDEIBiblio/Controllers/HelperController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;
using IDEIBiblio.AuthorizeAttributes;
using System.IO;

namespace IDEIBiblio.Controllers
{
    public class HelperController : Controller
    {
        [AuthorizeRole]
        public ActionResult UploadPicture()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult UploadPicture(HttpPostedFileBase file)
        {

            string fileLocation = "/Images/uploads/";
            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/uploads"), fileName);
                file.SaveAs(path);
                fileLocation += fileName;
            }

            return Json(new { url = fileLocation });
        }
    }
}

IDEIBiblio/IDEIBiblio/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIBiblio.Models;
using IDEIBiblio.AuthorizeAttributes;

namespace IDEIBiblio.Controllers
{
    public class MagazineController : Controller
    {
        private IDEIBiblioDbContext db = new IDEIBiblioDbContext();

        //
        // GET: /Magazine/

        public ActionResult Index()
        {
            ViewBag.Title = "Magazines";
            ViewBag.Message = "Featured:";
            return View(db.Magazines.ToList());
        }

        //
        // GET: /Default1/

        public ActionResult Featured()
        {
            ViewBag.Title = "Magazines";
            ViewBag.Message = "Featured:";
            ICollection<Magazine> Magazines = db.GetMostOrderedMagazines();
            return PartialView(Magazines);
        }

        //
        // GET: /Magazine/Details/5

        public ActionResult Details(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            ViewBag.Discount = magazine.DiscountPercentage * 100;
            return View(magazine);
        }

        //
        // GET: /Magazine/Create
        [AuthorizeRole]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Magazine/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Magazine magazine)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(magazine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(magazine);
        }

        //
        // GET: /Magazine/Edit/5
        [AuthorizeRole]
        public ActionResult Edit(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            return View(magazine);
        }

        //
        // POST: /Magazine/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Magazine magazine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(magazine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(magazine);
        }

        //
        // GET: /Magazine/Delete/5
        [AuthorizeRole]
        public ActionResult Delete(int id = 0)
        {
            Magazine magazine = db.Magazines.Find(id);
            if (magazine == null)
            {
                return HttpNotFound();
            }
            return View(magazine);
        }

        //
        // POST: /Magazine/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Magazine magazine = db.Magazines.Find(id);
            db.Products.Remove(magazine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIBiblio/IDEIBiblio/Views/Magazine/Create.cshtml
@model IDEIBiblio.Models.Magazine

@{
    ViewBag.Title ="Create";
}
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
@Scripts.Render("~/bundles/jqueryui")

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Book</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.EditionNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EditionNumber)
            @Html.ValidationMessageFor(model => model.EditionNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageURL)
        </div>
        <div class="editor-label">
            <img id="Image" src="" />            
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageURL)
            @Html.ValidationMessageFor(model => model.ImageURL)
            <a class="modalCreate" href="@Url.Action("UploadPicture","Helper")" onclick="return false;">Upload a new photo</a>
        </div>       
        
        <div class="editor-label">
            @Html.LabelFor(model => model.PublishingDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PublishingDate)
            @Html.ValidationMessageFor(model => model.PublishingDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, 5, 1, null)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CurrentPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurrentPrice)
            @Html.ValidationMessageFor(model => model.CurrentPrice)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<script type="text/javascript">

    function updatePicture(data) {
        var element = "ImageURL";
        var image = "Image";
        var url = data.url;


        $('#' + image).attr('src', url);
        $('#' + element).val(url);
        $('#popup').dialog('close');
    }

    $(document).ready(function () {
        $(".modalCreate").click(function (event) {
            event.stopPropagation();
            var title = $(this).text() + ':';
            var link = $(this).attr('href');
            $.get(link, {}, function (resp) {
                $('#popup').html(resp);
            });
            $("#popup").dialog({
                width: 400,
                height: 200,
                title: title,
                modal: true,

            });
        });
    });
</script>
<div id="popup"></div>
    

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IDEIBiblio/IDEIBiblio/Views/Magazine/Delete.cshtml
@model IDEIBiblio.Models.Magazine
@using IDEIBiblio.Helpers

@{
    ViewBag.Title = "Delete";
}

<h2>Delete?</h2>

<h3>Are you sure?</h3>
<fieldset>
    <legend>Book</legend>
    @Html.DisplayForProduct(Model)
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

IDEIBiblio/IDEIBiblio/Views/Magazine/Details.cshtml
@using IDEIBiblio.Helpers
@model IDEIBiblio.Models.Magazine


@{
    ViewBag.Title = Model.Name;
    ViewBag.Message = '#'+ Model.EditionNumber;
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<fieldset>
    <legend>Book</legend>
    <div class="productview-group">
        <div class="productview-image">
            <img alt="Product cover" class="image" src="@Model.ImageURL" />
        </div>

        <div class="productview-cell">
            <div class="productview-item">
                <div class="productview-label">
                     @Html.DisplayNameFor(model => model.EditionNumber)
                </div>
                <div class="productview-field">
                    @Html.DisplayFor(model => model.EditionNumber)
                </div>
            </div>
    
            <div class="productview-item">
                <div class="productview-label">
                     @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="productview-field">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>

             <div class="productview-item">
                <div class="productview-label">
                     @Html.DisplayNameFor(model => model.PublishingDate)
                </div>
                <div class="productview-field">
                    @Html.DisplayFor(model => model.PublishingDate)
                </div>
            </div>

            <div class="productview-item">    
                <div class="productview-label">
                     @Html.DisplayNameFor(model => model.CurrentPrice)
                </div>
                <div class="productview-field">
                    @Html.DisplayFor(model => model.CurrentPrice)
                </div>
                <div class="productview-label">
                     @Html.DisplayNameFor(model => model.DiscountPercentage)
                </div>
                <div class="productview-field">
                    @ViewBag.Discount %
                </div>
            </div>

           
    
            
        </div>
    </div>
</fieldset>
<p>
    @Html.AuthorizedActionLink("Edit", "Edit", new { id=Model.ProductID })|
    @Html.AuthorizedActionLink("Delete", "Delete", new { id=Model.ProductID })|
    @Html.ActionLink("Back to List", "Index")
</p>

IDEIBiblio/IDEIBiblio/Views/Magazine/Edit.cshtml
@model IDEIBiblio.Models.Magazine

@{
    ViewBag.Title = "Edit";
}
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
@Scripts.Render("~/bundles/jqueryui")

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Book</legend>
        @Html.HiddenFor(model => model.ProductID)

        
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.EditionNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EditionNumber)
            @Html.ValidationMessageFor(model => model.EditionNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageURL)
        </div>
        <div class="editor-label">
            <img id="Image" src="@Model.ImageURL" />            
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageURL)
            @Html.ValidationMessageFor(model => model.ImageURL)
            <a class="modalCreate" href="@Url.Action("UploadPicture", "Helper")" onclick="return false;">Upload a new photo</a>
        </div>        
        
        <div class="editor-label">
            @Html.LabelFor(model => model.PublishingDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PublishingDate)
            @Html.ValidationMessageFor(model => model.PublishingDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, 5, 1, null)
            @Html.ValidationMessageFor(model => model.Description)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.CurrentPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurrentPrice)
            @Html.ValidationMessageFor(model => model.CurrentPrice)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<script type="text/javascript">

    function updatePicture(data) {
        var element = "ImageURL";
        var image = "Image";
        var url = data.url;


        $('#' + image).attr('src', url);
        $('#' + element).val(url);
        $('#popup').dialog('close');
    }

    $(document).ready(function () {
        $(".modalCreate").click(function (event) {
            event.stopPropagation();
            var title = $(this).text() + ':';
            var link = $(this).attr('href');
            $.get(link, {}, function (resp) {
                $('#popup').html(resp);
            });
            $("#popup").dialog({
                width: 400,
                height: 200,
                title: title,
                modal: true,

            });
        });
    });
</script>
<div id="popup"></div>
    

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IDEIBiblio/IDEIBiblio/Views/Magazine/Featured.cshtml
@using IDEIBiblio.Helpers
@model IEnumerable<IDEIBiblio.Models.Magazine>

<div class="book-grid">
    @foreach (var item in Model) {
        @Html.DisplayForProduct(item);
    }
</div>

IDEIBiblio/IDEIBiblio/Views/Magazine/Index.cshtml
@using IDEIBiblio.Helpers
@model IEnumerable<IDEIBiblio.Models.Magazine>



<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>
<p>
    @Html.AuthorizedActionLink("Create New", "Create")
</p>

<div class="book-grid">
    @foreach (var item in Model) {
        @Html.DisplayForProduct(item);
    }
</div>